package com.ooooyt.babycommander.ui.tui;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Reproduces the "content generated by {@code /history} is hidden" symptom.
 *
 * <p>The right panel's auto-scroll relies on two volatile flags ({@code autoScroll}
 * and {@code dirty}) that are set by the event-bus consumer (vert.x event loop)
 * and consumed/cleared by the redraw loop (tui-thread). When a message arrives
 * <em>during</em> a redraw &mdash; after the renderer's snapshot is taken but
 * before {@code model.dirty = false} runs &mdash; both signals are clobbered:
 * <ul>
 *   <li>{@code autoScroll=true} (set by the message) is overwritten by the
 *       renderer's {@code autoScroll = false} consume;</li>
 *   <li>{@code dirty=true} (set by the message) is overwritten by the idle
 *       loop's {@code dirty = false}.</li>
 * </ul>
 * The net effect: no further redraw is ever scheduled, and {@code chatScroll}
 * stays at the max-scroll of the <em>stale</em> snapshot, so the freshly
 * appended history lines (footer + last tasks) remain below the visible area.
 *
 * <p>These tests pin the flawed interleaving deterministically (no real
 * concurrency needed) so the fix can be verified against the exact same steps.
 */
class HistoryScrollRaceTest {

    /** Replicates {@link TuiRenderer#drawDisplayRegion}'s scroll bookkeeping. */
    private static int applyScrollLogic(TuiModel model, int snapshotSize) {
        if (model.autoScroll) {
            model.chatScroll = Integer.MAX_VALUE;
            model.autoScroll = false;
        }
        int maxScroll = Math.max(0, snapshotSize - (model.bodyH() + 1));
        model.chatScroll = Math.max(0, Math.min(model.chatScroll, maxScroll));
        return maxScroll;
    }

    @Test
    void flaw_messageArrivingDuringRedrawHidesContentAndStalls() {
        TuiModel model = new TuiModel();
        model.tw = 80;
        model.th = 14;            // bodyH() = 8  -> visible right-panel lines = 9
        for (int i = 0; i < 20; i++) {   // 20 rendered lines already overflow the panel
            model.chatMessages.add(new ChatMessage("old" + i, "old" + i));
        }

        // --- Simulate the renderer's snapshot (taken under the chatMessages lock) ---
        List<ChatMessage> snapshot = List.copyOf(model.chatMessages);
        int snapshotSize = snapshot.size();

        // === DURING the (slow) rendering, the vert.x event loop delivers a new
        //     message — exactly what /history does when it publishes its lines. ===
        model.chatMessages.add(new ChatMessage("footer", "footer"));
        model.autoScroll = true;   // event loop: "please scroll to bottom"
        model.dirty = true;        // event loop: "please redraw"

        // --- Renderer finishes and applies its scroll logic (stale snapshot) ---
        applyScrollLogic(model, snapshotSize);

        // --- Idle loop clears dirty, clobbering the signal set above ---
        model.dirty = false;

        int realMaxScroll = Math.max(0, model.chatMessages.size() - (model.bodyH() + 1));

        // The bug: autoScroll consumed, dirty lost, chatScroll stuck at stale max.
        assertFalse(model.autoScroll, "autoScroll was clobbered by the renderer's consume");
        assertFalse(model.dirty, "dirty was clobbered by the idle loop's dirty=false");
        assertTrue(model.chatScroll < realMaxScroll,
            "chatScroll=" + model.chatScroll + " should be below real maxScroll=" + realMaxScroll
                + " — the footer is hidden and no redraw will ever reveal it");
    }

    /**
     * Mirrors the {@link TerminalSession} reconcile logic ({@code chatVersion}
     * sampled before/after a redraw) to prove the fix schedules a follow-up
     * redraw that scrolls to the bottom even when the message lands mid-render.
     */
    @Test
    void fix_versionSamplingReArmsAndRecoversScroll() {
        TuiModel model = new TuiModel();
        model.tw = 80;
        model.th = 14;            // bodyH() = 8 -> 9 visible lines
        for (int i = 0; i < 20; i++) {
            model.chatMessages.add(new ChatMessage("old" + i, "old" + i));
        }
        int bh = model.bodyH();

        // --- Idle redraw begins: sample chatVersion BEFORE rendering ---
        int versionBefore = model.chatVersion;

        // Snapshot taken (20 messages), then slow rendering begins ...
        int snapshotSize = model.chatMessages.size();

        // === Mid-render: the event loop appends the /history footer ===
        synchronized (model.chatMessages) {
            model.chatMessages.add(new ChatMessage("footer", "footer"));
            model.chatVersion++;        // the fix's signal
        }
        model.autoScroll = true;
        model.dirty = true;

        // Renderer applies its (stale) scroll logic — autoScroll is consumed.
        applyScrollLogic(model, snapshotSize);

        // === The fix: reconcile against chatVersion AFTER the redraw ===
        if (model.chatVersion != versionBefore) {
            model.autoScroll = true;    // re-arm: renderer's consume is undone
            model.dirty = true;         // re-arm: idle loop won't clear dirty
        } else {
            model.dirty = false;
        }

        assertTrue(model.dirty, "dirty re-armed so a follow-up redraw is scheduled");
        assertTrue(model.autoScroll, "autoScroll re-armed so the follow-up scrolls to bottom");

        // --- Follow-up redraw: fresh snapshot now includes the footer ---
        int freshSnapshot = model.chatMessages.size();          // 21
        applyScrollLogic(model, freshSnapshot);

        int realMaxScroll = Math.max(0, freshSnapshot - (bh + 1));
        assertEquals(realMaxScroll, model.chatScroll,
            "second pass scrolled to the bottom — the footer is now visible");
    }
}
